var db = require('./db');
var bcrypt = require('bcryptjs');

function seed() {
    // Check if already seeded
    if (db.count('users') > 0) {
        console.log('Database already seeded (' + db.count('users') + ' users). Skipping.');
        console.log('To reseed, delete gprn-data.json and run again.');
        return;
    }

    console.log('Seeding database...');

    var SALT_ROUNDS = 10;

    // ---- Locums ----
    var locums = [
        { id: 'loc-001', email: 'sarah.williams@gprn.wales', password: 'Locum2026!', role: 'locum', profile: { title: 'Dr', firstName: 'Sarah', lastName: 'Williams', phone: '07891 234567', gmcNumber: '7612345', medicalSchool: 'Cardiff University', yearQualified: 2015, performerList: true, nhsPension: true, computerSystems: ['EMIS', 'Vision'], signingScripts: 'Will sign scripts', healthBoards: ['Cardiff and Vale', 'Cwm Taf Morgannwg', 'Aneurin Bevan'], preferredShiftTypes: ['AM', 'PM', 'Full Day'], travelDistance: 30, bio: 'Experienced GP with over 8 years of locum experience across South Wales.', bookingReliability: 98, responseTime: '1-2 days', totalShifts: 156, rates: { am: 430, pm: 430, fullDay: 820, onCall: 50, housecall: 0 }, practiceRates: {}, documents: { indemnity: { uploaded: true, name: 'Indemnity_Certificate_2026.pdf', expiry: '2026-09-15' }, performerListStatus: { uploaded: true, name: 'Performer_List_Confirmation.pdf', expiry: null }, dbs: { uploaded: true, name: 'DBS_Enhanced_Check.pdf', expiry: '2026-12-01' }, cv: { uploaded: true, name: 'Dr_Williams_CV.pdf', expiry: null } } }},
        { id: 'loc-002', email: 'rhys.parry@gprn.wales', password: 'RhysGP2024', role: 'locum', profile: { title: 'Dr', firstName: 'Rhys', lastName: 'Parry', phone: '07456 789012', gmcNumber: '7623456', medicalSchool: 'Swansea University', yearQualified: 2012, performerList: true, nhsPension: false, computerSystems: ['EMIS'], signingScripts: 'Will sign scripts', healthBoards: ['Swansea Bay', 'Hywel Dda', 'Cwm Taf Morgannwg'], preferredShiftTypes: ['Full Day'], travelDistance: 40, bio: 'Senior locum GP with extensive experience in chronic disease management.', bookingReliability: 95, responseTime: '< 1 day', totalShifts: 230, rates: { am: 450, pm: 450, fullDay: 850, onCall: 60, housecall: 15 }, practiceRates: {}, documents: { indemnity: { uploaded: true, name: 'Indemnity_2026.pdf' }, performerListStatus: { uploaded: true, name: 'PL_Status.pdf' }, dbs: { uploaded: true, name: 'DBS_Check.pdf' }, cv: { uploaded: true, name: 'CV_Dr_Parry.pdf' } } }},
        { id: 'loc-003', email: 'megan.jones@gprn.wales', password: 'MeganJ!456', role: 'locum', profile: { title: 'Dr', firstName: 'Megan', lastName: 'Jones', phone: '07723 456789', gmcNumber: '7634567', medicalSchool: 'University of Bristol', yearQualified: 2018, performerList: true, nhsPension: true, computerSystems: ['Vision', 'TPP'], signingScripts: 'Would negotiate a separate fee', healthBoards: ['Betsi Cadwaladr', 'Powys'], preferredShiftTypes: ['AM', 'PM'], travelDistance: 25, bio: 'Enthusiastic GP locum based in North Wales.', bookingReliability: 100, responseTime: '< 1 day', totalShifts: 78, rates: { am: 400, pm: 400, fullDay: 780, onCall: 40, housecall: 0 }, practiceRates: {}, documents: { indemnity: { uploaded: true, name: 'Indemnity_MJ.pdf' }, performerListStatus: { uploaded: true, name: 'Performer_List.pdf' }, dbs: { uploaded: false, name: null }, cv: { uploaded: true, name: 'CV_Megan_Jones.pdf' } } }},
        { id: 'loc-004', email: 'owen.davies@gprn.wales', password: 'OwenD#2023', role: 'locum', profile: { title: 'Dr', firstName: 'Owen', lastName: 'Davies', phone: '07934 567890', gmcNumber: '7645678', medicalSchool: 'Cardiff University', yearQualified: 2010, performerList: true, nhsPension: true, computerSystems: ['EMIS', 'Vision', 'TPP'], signingScripts: 'Will sign scripts', healthBoards: ['Cardiff and Vale', 'Aneurin Bevan', 'Cwm Taf Morgannwg', 'Swansea Bay'], preferredShiftTypes: ['AM', 'PM', 'Full Day', 'On-Call'], travelDistance: 50, bio: 'Versatile and highly experienced locum GP covering all of South Wales.', bookingReliability: 82, responseTime: '1-2 days', totalShifts: 312, rates: { am: 420, pm: 420, fullDay: 800, onCall: 55, housecall: 10 }, practiceRates: {}, documents: { indemnity: { uploaded: true, name: 'Indemnity_OD.pdf' }, performerListStatus: { uploaded: true, name: 'PL_OD.pdf' }, dbs: { uploaded: true, name: 'DBS_OD.pdf' }, cv: { uploaded: true, name: 'CV_Owen_Davies.pdf' } } }},
        { id: 'loc-005', email: 'elin.morgan@gprn.wales', password: 'ElinM@Wales', role: 'locum', profile: { title: 'Dr', firstName: 'Elin', lastName: 'Morgan', phone: '07612 345678', gmcNumber: '7656789', medicalSchool: 'University of Liverpool', yearQualified: 2019, performerList: true, nhsPension: true, computerSystems: ['EMIS'], signingScripts: 'Will sign scripts', healthBoards: ['Hywel Dda', 'Swansea Bay'], preferredShiftTypes: ['AM', 'Full Day'], travelDistance: 20, bio: 'Welsh-speaking GP locum based in West Wales.', bookingReliability: 100, responseTime: '< 1 day', totalShifts: 45, rates: { am: 410, pm: 410, fullDay: 790, onCall: 45, housecall: 0 }, practiceRates: {}, documents: { indemnity: { uploaded: true, name: 'Indemnity_EM.pdf' }, performerListStatus: { uploaded: true, name: 'PL_EM.pdf' }, dbs: { uploaded: true, name: 'DBS_EM.pdf' }, cv: { uploaded: true, name: 'CV_Elin_Morgan.pdf' } } }},
        { id: 'loc-006', email: 'james.evans@gprn.wales', password: 'JamesE!789', role: 'locum', profile: { title: 'Dr', firstName: 'James', lastName: 'Evans', phone: '07845 678901', gmcNumber: '7667890', medicalSchool: 'Peninsula Medical School', yearQualified: 2016, performerList: true, nhsPension: false, computerSystems: ['Vision'], signingScripts: 'Would negotiate a separate fee', healthBoards: ['Aneurin Bevan', 'Cardiff and Vale'], preferredShiftTypes: ['PM', 'Full Day'], travelDistance: 35, bio: 'Experienced GP with a focus on mental health and substance misuse.', bookingReliability: 74, responseTime: '2-3 days', totalShifts: 189, rates: { am: 440, pm: 440, fullDay: 840, onCall: 60, housecall: 12 }, practiceRates: {}, documents: { indemnity: { uploaded: true, name: 'Indemnity_JE.pdf' }, performerListStatus: { uploaded: true, name: 'PL_JE.pdf' }, dbs: { uploaded: true, name: 'DBS_JE.pdf' }, cv: { uploaded: false, name: null } } }},
        { id: 'loc-007', email: 'carys.thomas@gprn.wales', password: 'CarysT#2025', role: 'locum', profile: { title: 'Dr', firstName: 'Carys', lastName: 'Thomas', phone: '07567 890123', gmcNumber: '7678901', medicalSchool: 'Cardiff University', yearQualified: 2020, performerList: true, nhsPension: true, computerSystems: ['EMIS', 'Vision'], signingScripts: 'Will sign scripts', healthBoards: ['Cwm Taf Morgannwg', 'Cardiff and Vale', 'Swansea Bay'], preferredShiftTypes: ['AM', 'PM'], travelDistance: 20, bio: 'Newly qualified GP eager to build locum experience.', bookingReliability: 100, responseTime: '< 1 day', totalShifts: 23, rates: { am: 380, pm: 380, fullDay: 720, onCall: 35, housecall: 0 }, practiceRates: {}, documents: { indemnity: { uploaded: true, name: 'Indemnity_CT.pdf' }, performerListStatus: { uploaded: true, name: 'PL_CT.pdf' }, dbs: { uploaded: true, name: 'DBS_CT.pdf' }, cv: { uploaded: true, name: 'CV_Carys_Thomas.pdf' } } }},
        { id: 'loc-008', email: 'gareth.hughes@gprn.wales', password: 'GarethH!101', role: 'locum', profile: { title: 'Dr', firstName: 'Gareth', lastName: 'Hughes', phone: '07378 901234', gmcNumber: '7689012', medicalSchool: 'University of Manchester', yearQualified: 2008, performerList: true, nhsPension: true, computerSystems: ['EMIS', 'TPP'], signingScripts: 'Will sign scripts', healthBoards: ['Betsi Cadwaladr', 'Powys', 'Hywel Dda'], preferredShiftTypes: ['Full Day', 'On-Call'], travelDistance: 60, bio: 'Senior GP covering North and Mid Wales. Extensive rural practice experience.', bookingReliability: 91, responseTime: '1-2 days', totalShifts: 410, rates: { am: 460, pm: 460, fullDay: 880, onCall: 70, housecall: 20 }, practiceRates: {}, documents: { indemnity: { uploaded: true, name: 'Indemnity_GH.pdf' }, performerListStatus: { uploaded: true, name: 'PL_GH.pdf' }, dbs: { uploaded: true, name: 'DBS_GH.pdf' }, cv: { uploaded: true, name: 'CV_Gareth_Hughes.pdf' } } }}
    ];

    // ---- Practices ----
    var practices = [
        { id: 'prac-001', email: 'manager@ringland.wales', password: 'Practice2026!', role: 'practice', profile: { practiceName: 'Ringland Medical Practice', healthBoard: 'Aneurin Bevan', address: 'TRHills Health & Wellbein, 282 Ringland Circle', city: 'Newport', postcode: 'NP9 9PS', phone: '01633 274000', website: 'https://ringlandmedical.wales', computerSystem: 'EMIS', partners: 4, patientListSize: 8500, contactName: 'Jane Morgan', contactRole: 'Practice Manager', contactEmail: 'manager@ringland.wales', contactPhone: '01633 274001' }},
        { id: 'prac-002', email: 'admin@whitchurchroad.wales', password: 'Whitchurch!22', role: 'practice', profile: { practiceName: 'Whitchurch Road Surgery', healthBoard: 'Cardiff and Vale', address: '145 Whitchurch Road', city: 'Cardiff', postcode: 'CF14 3JN', phone: '029 2061 5000', website: 'https://whitchurchroadsurgery.wales', computerSystem: 'Vision', partners: 6, patientListSize: 12000, contactName: 'David Lloyd', contactRole: 'Practice Manager', contactEmail: 'admin@whitchurchroad.wales', contactPhone: '029 2061 5001' }},
        { id: 'prac-003', email: 'admin@radyrmedical.wales', password: 'Radyr#Med34', role: 'practice', profile: { practiceName: 'Radyr Medical Centre', healthBoard: 'Cardiff and Vale', address: '34 Station Road', city: 'Cardiff', postcode: 'CF15 8AA', phone: '029 2084 2000', website: 'https://radyrmedical.wales', computerSystem: 'EMIS', partners: 3, patientListSize: 6200, contactName: 'Helen Price', contactRole: 'Practice Manager', contactEmail: 'admin@radyrmedical.wales', contactPhone: '029 2084 2001' }},
        { id: 'prac-004', email: 'admin@malpasbrook.wales', password: 'Malpas!Brook5', role: 'practice', profile: { practiceName: 'Malpas Brook Health Centre', healthBoard: 'Aneurin Bevan', address: 'Pilton Vale', city: 'Newport', postcode: 'NP20 6WB', phone: '01633 855200', website: '', computerSystem: 'EMIS', partners: 5, patientListSize: 9800, contactName: 'Karen Richards', contactRole: 'Assistant Practice Manager', contactEmail: 'admin@malpasbrook.wales', contactPhone: '01633 855201' }},
        { id: 'prac-005', email: 'admin@trosnant.wales', password: 'Trosnant#66', role: 'practice', profile: { practiceName: 'Trosnant Lodge', healthBoard: 'Aneurin Bevan', address: 'Trosnant Street', city: 'Pontypool', postcode: 'NP4 8AT', phone: '01495 762200', website: '', computerSystem: 'Vision', partners: 3, patientListSize: 5400, contactName: 'Susan Evans', contactRole: 'Practice Manager', contactEmail: 'admin@trosnant.wales', contactPhone: '01495 762201' }},
        { id: 'prac-006', email: 'admin@bridgmoresurgery.wales', password: 'Bridgmore!77', role: 'practice', profile: { practiceName: 'Bridgmore Surgery', healthBoard: 'Cardiff and Vale', address: '12 Bridge Street', city: 'Cardiff', postcode: 'CF11 6NR', phone: '029 2039 5000', website: '', computerSystem: 'EMIS', partners: 4, patientListSize: 7600, contactName: 'Tom Jenkins', contactRole: 'Practice Manager', contactEmail: 'admin@bridgmore.wales', contactPhone: '029 2039 5001' }},
        { id: 'prac-007', email: 'admin@kingsroad.wales', password: 'KingsRd#88', role: 'practice', profile: { practiceName: 'Kings Road Surgery', healthBoard: 'Cardiff and Vale', address: '88 Kings Road', city: 'Cardiff', postcode: 'CF11 9DE', phone: '029 2023 4000', website: '', computerSystem: 'EMIS', partners: 2, patientListSize: 4200, contactName: 'Ann Thomas', contactRole: 'Practice Manager', contactEmail: 'admin@kingsroad.wales', contactPhone: '029 2023 4001' }},
        { id: 'prac-008', email: 'admin@clydach.wales', password: 'Clydach!99', role: 'practice', profile: { practiceName: 'Clydach Primary Care Centre', healthBoard: 'Swansea Bay', address: 'Clydach Health Centre, Centenary Way', city: 'Swansea', postcode: 'SA6 5EY', phone: '01792 843500', website: '', computerSystem: 'Vision', partners: 4, patientListSize: 8100, contactName: 'Lowri Griffiths', contactRole: 'Practice Manager', contactEmail: 'admin@clydach.wales', contactPhone: '01792 843501' }},
        { id: 'prac-009', email: 'admin@porttalbot.wales', password: 'PortT#2026', role: 'practice', profile: { practiceName: 'Port Talbot Medical Practice', healthBoard: 'Swansea Bay', address: '15 Commercial Road', city: 'Port Talbot', postcode: 'SA13 1LN', phone: '01639 882400', website: '', computerSystem: 'EMIS', partners: 3, patientListSize: 5800, contactName: 'Mark Edwards', contactRole: 'Practice Manager', contactEmail: 'admin@porttalbot.wales', contactPhone: '01639 882401' }},
        { id: 'prac-010', email: 'admin@wrexhamtown.wales', password: 'Wrexham!Town', role: 'practice', profile: { practiceName: 'Wrexham Town Surgery', healthBoard: 'Betsi Cadwaladr', address: '22 Regent Street', city: 'Wrexham', postcode: 'LL11 1RY', phone: '01978 291500', website: '', computerSystem: 'TPP', partners: 5, patientListSize: 11200, contactName: 'Bethan Williams', contactRole: 'Practice Manager', contactEmail: 'admin@wrexhamtown.wales', contactPhone: '01978 291501' }},
        { id: 'prac-011', email: 'admin@aberystwyth.wales', password: 'Aber#Med123', role: 'practice', profile: { practiceName: 'Aberystwyth Medical Centre', healthBoard: 'Hywel Dda', address: 'Padarn Surgery, Llanbadarn Road', city: 'Aberystwyth', postcode: 'SY23 1EY', phone: '01970 624500', website: '', computerSystem: 'EMIS', partners: 3, patientListSize: 6800, contactName: 'Sian Roberts', contactRole: 'Practice Manager', contactEmail: 'admin@aberystwyth.wales', contactPhone: '01970 624501' }},
        { id: 'prac-012', email: 'admin@brecon.wales', password: 'Brecon!Med45', role: 'practice', profile: { practiceName: 'Brecon Medical Practice', healthBoard: 'Powys', address: 'Cerrigochion Road', city: 'Brecon', postcode: 'LD3 7AB', phone: '01874 622131', website: '', computerSystem: 'Vision', partners: 2, patientListSize: 3900, contactName: 'Gareth Rees', contactRole: 'Practice Manager', contactEmail: 'admin@brecon.wales', contactPhone: '01874 622132' }}
    ];

    // Insert users
    var allUsers = locums.concat(practices);
    for (var i = 0; i < allUsers.length; i++) {
        var u = allUsers[i];
        var hash = bcrypt.hashSync(u.password, SALT_ROUNDS);
        db.insert('users', {
            id: u.id,
            email: u.email,
            password_hash: hash,
            role: u.role,
            profile: u.profile,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString()
        });
    }
    console.log('Seeded ' + locums.length + ' locums and ' + practices.length + ' practices');

    // Force save to disk
    db.saveNow();
    console.log('Database seeding complete!');
}

// Run if called directly
if (require.main === module) {
    seed();
}

module.exports = seed;
